_welcome:
    path:     /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }


_welcometest:
    path:     /test
    defaults: { _controller: AcmeDemoBundle:Welcometest:index }



_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

   
    


